### PR TITLE
Add YM2151 busy wait

### PR DESCRIPTION
**Pull request by rossato**
This resolves issue #7.  I have checked it on FPGA hardware and on the emulator.

### CODE REVIEW

**Comment by SlithyMatt** [comment]
I would prefer not to have unnamed labels in this code, as it is shared between projects and this practice can result in easy breakage. If you could refactor this with cheap locals (starting with @), that would be appreciated. Otherwise, I'll re-implement the changes myself on the master.  Thanks!

**Comment by rossato** [comment]
Unfortunately named labels don't work inside macros.  I could refactor to make YM_set_reg a function and have the writes in soundfx.asm and music.asm call it if you want, but it would be a larger change and I didn't want to tinker with your code too much without your permission.

**Comment by SlithyMatt** [comment]
Sorry, I see that I was confusing the changes. I see you simply added to the unnamed labels where I already had them. I thought they were getting added to music.asm, but I see now that's not the case. I will look at them more closely. Thanks!

**Comment by rossato** [comment]
Sorry I polluted my master branch with the joystick issue.  I'm working to back it out, I might trash this PR in the process.

**Pull request closed without merging**
